// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFCi2Ta-EMAzC2du1MMHd-cPfbajbbgg',
    appId: '1:218825347947:web:844e9a959186f68433722e',
    messagingSenderId: '218825347947',
    projectId: 'ai-mock-interviewer-d1d08',
    authDomain: 'ai-mock-interviewer-d1d08.firebaseapp.com',
    storageBucket: 'ai-mock-interviewer-d1d08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP1NzStDUwtbTIZRDZVHAJW9lF0hpndME',
    appId: '1:218825347947:android:f9865c8be26673cd33722e',
    messagingSenderId: '218825347947',
    projectId: 'ai-mock-interviewer-d1d08',
    storageBucket: 'ai-mock-interviewer-d1d08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHi-fB8H7GTwPi3MyZf6MnRmQn0YWZGSQ',
    appId: '1:218825347947:ios:2e37267c137e194f33722e',
    messagingSenderId: '218825347947',
    projectId: 'ai-mock-interviewer-d1d08',
    storageBucket: 'ai-mock-interviewer-d1d08.firebasestorage.app',
    iosClientId: '218825347947-hknnraq35chqa730h42d78p25caj5gqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiMockInterviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHi-fB8H7GTwPi3MyZf6MnRmQn0YWZGSQ',
    appId: '1:218825347947:ios:2e37267c137e194f33722e',
    messagingSenderId: '218825347947',
    projectId: 'ai-mock-interviewer-d1d08',
    storageBucket: 'ai-mock-interviewer-d1d08.firebasestorage.app',
    iosClientId: '218825347947-hknnraq35chqa730h42d78p25caj5gqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiMockInterviewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzFCi2Ta-EMAzC2du1MMHd-cPfbajbbgg',
    appId: '1:218825347947:web:1db61fc09d64dab233722e',
    messagingSenderId: '218825347947',
    projectId: 'ai-mock-interviewer-d1d08',
    authDomain: 'ai-mock-interviewer-d1d08.firebaseapp.com',
    storageBucket: 'ai-mock-interviewer-d1d08.firebasestorage.app',
  );
}
